<?php

/**
 * Magento 2 extension for Cashew Payments
 */

/** @var $block DotCommerce\CashewPayments\Block\Product\View\Installment */

$price = number_format($block->getPrice());
?>

<div id="cashew-widget" data-amount="<?= $price ?>" data-currency="<?= $block->getCurrency() ?>" data-language="<?= $block->getLang() ?>"></div>
<script src="https://s3-eu-west-1.amazonaws.com/cdn-dev.cashewpayments.com/widgets/magento.widget.min.js"></script>
