<?php

/**
 * Magento 2 extension for Cashew Payments
 */

/** @var $block DotCommerce\CashewPayments\Block\Product\View\Installment */
?>

<?php 
$allowedCurrencies = ['AED', 'SAR'];

if ($block->isEnabled() && 
in_array($block->getCurrency(), $allowedCurrencies) && 
($block->getLang() === 'en' || $block->getLang() === 'ar')): ?>

    <div id="cashew-widget" data-amount="<?= number_format($block->getPrice()) ?>" data-currency="<?= $block->getCurrency() ?>" data-language="<?= $block->getLang() ?>"></div>
    <script src="<?= $block->getEnvironment() ?>widgets/magento.widget.min.js"></script>
<?php endif; ?>
